/**
 * Syncpack docs https://jamiemason.github.io/
 */

module.exports = {
	dependencyTypes: ['dev', 'overrides', 'pnpmOverrides', 'prod', 'resolutions'],
	filter: '.',
	indent: '  ',
	semverGroups: [],
	semverRange: '^',
	sortAz: [
		'contributors',
		'dependencies',
		'devDependencies',
		'keywords',
		'peerDependencies',
		'resolutions',
		'scripts',
	],
	sortFirst: [
		'name',
		'version',
		'description',
		'homepage',
		'bugs',
		'repository',
		'author',
		'contributors',
		'license',
		'private',
		'workspaces',
		'type',
		'import',
		'exports',
		'main',
		'types',
		'files',
		'scripts',
		'resolutions',
		'dependencies',
		'devDependencies',
		'peerDependencies',
		'packageManager',
		'engines',
	],
	sortPackages: true,
	source: ['apps/*/package.json', 'package.json', 'packages/**/package.json'],
	versionGroups: [],
}
